import { kv } from "@vercel/kv"
import { get } from "@vercel/blob"
import { embed } from "ai"
import { openai } from "@ai-sdk/openai"
import { createEdgeClient } from "../../../../lib/supabase-server"
import { validateEnv } from "../../../../lib/utils/env"
import { createClient } from "../../../../lib/pinecone/client"
import { chunkDocument } from "../../../../lib/documents/chunker"
